version: 2

sources:
  - name: raw_netflix
    schema: netflix
    tables:
      - name: raw_netflix_titles
        description: ""

  - name: api_netflix
    schema: netflix
    tables:
      - name: api_response_netflix
        description: ""